version: 1.0.{build}

environment:
  matrix:
    - nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g elm
  - npm install -g create-elm-app
    
build_script:
  - elm-package install --yes
  - elm-app build

deploy_script:
  - npm install -g firebase-tools
  - firebase deploy --non-interactive --only hosting --project %FIREBASE_PROJECT% --token="%FIREBASE_API_TOKEN%"
