version: 1.0.{build}

environment:
  matrix:
    - nodejs_version: "6.0"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g elm
  - npm install -g create-elm-app
    
build_script:
  - elm-package install --yes
  - elm-app build
